// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit
export const ADDRESSES = {
  "DemoUSD": "0x959a3d1dae0716a90106f0ce0b8e9dec6d7fab24",
  "ComplianceRegistry": "0x5a72a93162744ce855b8f725cf90dd9b60895f5a",
  "DiligencePortal": "0x9772ddb66adcd7a6da53550349303862854012e3",
  "RWAComplianceReceiver": "0x85b96e5aa8414560613daa5c51ee6b058b041075",
  "RWAVault": "0xa5886b1b554f44674ab1303b4730f100840a791a",
  "IdentityRegistry": "0x0e99c1638b6f1f2723d52467eb712a0829b036ca",
  "ReputationRegistry": "0xc613cc2481ddd81c731163fb2a05c793ca05c11d",
  "ValidationRegistry": "0xccce9d98d14df2b28998a956ee1f457f46d589ec"
} as const;
