// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit
export const ADDRESSES = {
  "DemoUSD": "0xff196f1e3a895404d073b8611252cf97388773a7",
  "ComplianceRegistry": "0xc36e784e1dff616bdae4eac7b310f0934faf04a4",
  "DiligencePortal": "0x8071e429c7684fce0250287f1578397142503241",
  "RWAComplianceReceiver": "0xb98e0fb673e5a0c6e15f1d0a9f36e7da954a0d5e",
  "RWAVault": "0x78da752e9dbd73a9b0c0f5ddd15e854d2b879524",
  "IdentityRegistry": "0x1cf34658e7df9a46ad61486d007a8d62aec9891e",
  "ReputationRegistry": "0x33d10f2449ffede92b43d4fba562f132ba6a766a",
  "ValidationRegistry": "0xb9818483d01ca0e721849703c58148cfb81328fc"
} as const;
