// Auto-sync script: reads broadcast/Deploy.s.sol/84532/run-latest.json
// and writes deployed addresses + ABIs into src/lib/contracts.ts
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..", "..");

const broadcastPath = join(root, "broadcast/Deploy.s.sol/84532/run-latest.json");
const broadcast = JSON.parse(readFileSync(broadcastPath, "utf8"));

const nameMap = {};
for (const tx of broadcast.transactions || []) {
  if (tx.contractName && tx.contractAddress) {
    nameMap[tx.contractName] = tx.contractAddress;
  }
}

const addresses = {
  DemoUSD: nameMap.DemoUSD,
  ComplianceRegistry: nameMap.ComplianceRegistry,
  DiligencePortal: nameMap.DiligencePortal,
  RWAComplianceReceiver: nameMap.RWAComplianceReceiver,
  RWAVault: nameMap.RWAVault,
  IdentityRegistry: nameMap.IdentityRegistry,
  ReputationRegistry: nameMap.ReputationRegistry,
  ValidationRegistry: nameMap.ValidationRegistry,
};

const out = `// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit
export const ADDRESSES = ${JSON.stringify(addresses, null, 2)} as const;
`;

writeFileSync(join(__dirname, "..", "src/lib/addresses.ts"), out);
console.log("Wrote src/lib/addresses.ts", addresses);
